@startuml Process View - Level 2

autonumber
skinparam packageStyle rect

title PUT object

participant "Front-End" as FE <<C4 Container>>
participant "Back-End" as BE <<C4 Container>>

-> FE: PUT request
activate FE
FE -> BE: PUT /object/{id} {new data}
activate BE
alt user authorized

    alt user authorized
        BE --> FE: Returns success message
        deactivate BE
        <-- FE: Displays success message
    
else user unauthorized

<-- FE: Sends message to client: unauthorized access (401)
else database unavailable
<-- FE: Sends message to client: service unavailable (503)
else invalid input

<-- FE: Sends message to client: bad request (400)

else object not found

<-- FE: Sends message to client: object not found (404)

end alt
deactivate FE

@enduml