@startuml Process View - Level 1

autonumber
skinparam packageStyle rect

title Delete Request

participant "System" as S <<system (C4)>>

-> S:DELETE request

activate S

alt success

  <-- S: object deleted successfully (200)

else unauthorized

  <-- S: unauthorized (401)

else unavailable server

  <-- S: service unavailable (503)

end

@enduml